name: 'Setup & initialize project environment'
description: 'Setup Bun, install dependencies, and initialize environment'

runs:
  using: 'composite'
  steps:
    - name: "Install & setup Bun"
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: bun install
