name: ci

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository (@v4)"
        uses: actions/checkout@v4

      - name: "Setup project & environment"
        uses: ./.github/actions/setup

      - name: Lint workspace
        run: bun lint:ws

      - name: Lint source
        run: bun lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository (@v4)"
        uses: actions/checkout@v4

      - name: "Setup project & environment"
        uses: ./.github/actions/setup

      - name: Run tests
        run: bun format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository (@v4)"
        uses: actions/checkout@v4

      - name: "Setup project & environment"
        uses: ./.github/actions/setup

      - name: Run tests
        run: bun typecheck
